from wordpress_api import WordPressAPI
from news_processor import CannabisNewsProcessor

# Test the full workflow with debugging
print("=== TESTING FULL WORKFLOW ===")

# Create API instance
wp_api = WordPressAPI()

# Test 1: Simple news post creation
print("\n1. Testing simple news post creation...")
result = wp_api.create_news_post(
    "Test Cannabis News Article", 
    "<p>This is a test cannabis news article content.</p>", 
    status='draft'
)

if result:
    print(f"✓ Created news post with ID: {result.get('id')}")
    print(f"✓ Post URL: {result.get('link')}")
    print(f"✓ Status: {result.get('status')}")
else:
    print("✗ Failed to create news post")

# Test 2: News post with categories and tags
print("\n2. Testing news post with categories and tags...")
result = wp_api.create_news_post(
    "Test Cannabis News with Categories", 
    "<p>This is a test with categories and tags.</p>", 
    status='draft',
    categories=['Cannabis News'],
    tags=['politics']
)

if result:
    print(f"✓ Created news post with categories/tags, ID: {result.get('id')}")
else:
    print("✗ Failed to create news post with categories/tags")

# Test 3: Try the full news processor
print("\n3. Testing full cannabis news processor...")
try:
    processor = CannabisNewsProcessor()
    article = processor.get_cannabis_article()
    
    if article:
        print(f"✓ Generated article: {article['title'][:50]}...")
        print(f"✓ Category: {article['category']}")
        print(f"✓ Tag: {article['tag']}")
        print(f"✓ Content length: {len(article['content'])} characters")
        
        # Try to post it
        result = wp_api.create_news_post(
            article['title'],
            article['content'],
            status='draft',
            categories=['Cannabis News'],
            tags=[article['tag']]
        )
        
        if result:
            print(f"✓ Posted article with ID: {result.get('id')}")
            print(f"✓ Check your WordPress News section!")
        else:
            print("✗ Failed to post generated article")
    else:
        print("✗ No article generated by processor")
        
except Exception as e:
    print(f"✗ Error in news processor: {e}")
    import traceback
    traceback.print_exc()